"""add whatsapp, email oauth, tally agent key

Revision ID: 06dcbbb37285
Revises: bfa92326ce4d
Create Date: 2026-08-25 19:29:27.486431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06dcbbb37285'
down_revision: Union[str, Sequence[str], None] = 'bfa92326ce4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_oauth_connections',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('whatsapp_connections',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('phone_number_id', sa.String(), nullable=False),
    sa.Column('business_account_id', sa.String(), nullable=False),
    sa.Column('encrypted_system_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.add_column('erp_connections', sa.Column('agent_key_hash', sa.String(), nullable=True))
    op.alter_column('erp_connections', 'host',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('erp_connections', 'port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('erp_connections', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_erp_connections_agent_key_hash'), 'erp_connections', ['agent_key_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_erp_connections_agent_key_hash'), table_name='erp_connections')
    op.alter_column('erp_connections', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('erp_connections', 'port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('erp_connections', 'host',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('erp_connections', 'agent_key_hash')
    op.drop_table('whatsapp_connections')
    op.drop_table('email_oauth_connections')
    # ### end Alembic commands ###
