"""add source provenance to component master

Revision ID: 2d56a377ab9b
Revises: c8410f5e5eb1
Create Date: 2026-08-25 16:22:03.139661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d56a377ab9b'
down_revision: Union[str, Sequence[str], None] = 'c8410f5e5eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate produced NOT NULL with no default, which would
    # reject against the already-populated table. Backfill existing
    # rows as "manual" (true for everything seeded/imported before
    # this column existed), then drop the server default -- new rows
    # already supply the value explicitly via the Python-side default.
    op.add_column(
        'components_master',
        sa.Column('source', sa.String(), nullable=False, server_default='manual')
    )
    op.alter_column('components_master', 'source', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components_master', 'source')
    # ### end Alembic commands ###
