"""add review action tracking to bom rows

Revision ID: c8410f5e5eb1
Revises: edc783a27e42
Create Date: 2026-08-25 14:44:52.229590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8410f5e5eb1'
down_revision: Union[str, Sequence[str], None] = 'edc783a27e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom_rows', sa.Column('review_action', sa.String(), nullable=True))
    op.add_column('bom_rows', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bom_rows', 'reviewed_at')
    op.drop_column('bom_rows', 'review_action')
    # ### end Alembic commands ###
