"""add quoted quantity for moq rounding visibility

Revision ID: bfa92326ce4d
Revises: eacc73afb877
Create Date: 2026-08-25 16:56:43.226921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa92326ce4d'
down_revision: Union[str, Sequence[str], None] = 'eacc73afb877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom_rows', sa.Column('quoted_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bom_rows', 'quoted_quantity')
    # ### end Alembic commands ###
