"""add organization rules, moq, quote expiry

Revision ID: eacc73afb877
Revises: 2d56a377ab9b
Create Date: 2026-08-25 16:55:20.858220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eacc73afb877'
down_revision: Union[str, Sequence[str], None] = '2d56a377ab9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_rules',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('quote_validity_hours', sa.Integer(), nullable=False),
    sa.Column('default_margin_percent', sa.Float(), nullable=False),
    sa.Column('moq_enforcement_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.add_column('bom_files', sa.Column('quote_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('components_master', sa.Column('moq', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components_master', 'moq')
    op.drop_column('bom_files', 'quote_expires_at')
    op.drop_table('organization_rules')
    # ### end Alembic commands ###
