"""add ERP connections and component pricing

Revision ID: edc783a27e42
Revises: 002e4ed3a178
Create Date: 2026-08-25 14:36:17.745747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc783a27e42'
down_revision: Union[str, Sequence[str], None] = '002e4ed3a178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'component_id', name='uq_component_price_org_component')
    )
    op.create_index(op.f('ix_component_prices_component_id'), 'component_prices', ['component_id'], unique=False)
    op.create_index(op.f('ix_component_prices_organization_id'), 'component_prices', ['organization_id'], unique=False)
    op.create_table('erp_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('erp_type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_connections_organization_id'), 'erp_connections', ['organization_id'], unique=False)
    op.add_column('bom_rows', sa.Column('unit_price', sa.Float(), nullable=True))
    op.add_column('bom_rows', sa.Column('line_total', sa.Float(), nullable=True))
    op.add_column('bom_rows', sa.Column('price_currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bom_rows', 'price_currency')
    op.drop_column('bom_rows', 'line_total')
    op.drop_column('bom_rows', 'unit_price')
    op.drop_index(op.f('ix_erp_connections_organization_id'), table_name='erp_connections')
    op.drop_table('erp_connections')
    op.drop_index(op.f('ix_component_prices_organization_id'), table_name='component_prices')
    op.drop_index(op.f('ix_component_prices_component_id'), table_name='component_prices')
    op.drop_table('component_prices')
    # ### end Alembic commands ###
